### ISSUE TITLE
UnboundLocalError: local variable 'm' referenced before assignment

### ISSUE THREAD

**Issue by ignatenkobrain** [openstack-packages/rdopkg#61]
```python
[ignatenko@ignatenko python-pygit2]$ ~/.local/bin/rdopkg patch
## get_package_env
## ensure_patches_branch
## reset_patches_branch
git update-ref refs/heads/master-patches refs/remotes/patches/master-patches
## fetch_patches_branch
## check_new_patches
## update_spec
## commit_distgit_update
git commit -a -F -
[master fbc7e32] Remove remote-calling unit tests
 1 file changed, 5 insertions(+), 1 deletion(-)
## update_patches
git checkout master-patches
git checkout master
No valid patch filtering regex found in the spec file.
git rm --ignore-unmatch 0001-Remove-remote-calling-unit-tests.patch

3 patches on top of v0.24.0, 0 excluded by base, 0 filtered out by regex.
4859d36  Remove remote-calling unit tests
7d296f3  repository: decode() linkname
a922ced  repository: SYMTYPE is constant in module tarfile, not in any class
git format-patch --no-renames --no-signature -N --ignore-submodules --start-number 1 a922ced~..4859d36
git add 0001-repository-SYMTYPE-is-constant-in-module-tarfile-not.patch
git add 0002-repository-decode-linkname.patch
git add 0003-Remove-remote-calling-unit-tests.patch
Traceback (most recent call last):
  File "/home/ignatenko/.local/bin/rdopkg", line 9, in <module>
    load_entry_point('rdopkg', 'console_scripts', 'rdopkg')()
  File "/home/ignatenko/git/upstream/rdopkg/rdopkg/shell.py", line 94, in main
    runner.engage()
  File "/home/ignatenko/git/upstream/rdopkg/rdopkg/core.py", line 172, in engage
    new_args = self.action_manager.run_action(step, self.args)
  File "/home/ignatenko/git/upstream/rdopkg/rdopkg/action.py", line 155, in run_action
    return action_fun(*fun_args)
  File "/home/ignatenko/git/upstream/rdopkg/rdopkg/actions.py", line 981, in update_patches
    spec.set_new_patches(patch_fns)
  File "/home/ignatenko/git/upstream/rdopkg/rdopkg/utils/specfile.py", line 296, in set_new_patches
    if not m:
UnboundLocalError: local variable 'm' referenced before assignment
```

**Comment by ignatenkobrain** [comment]
`Source:         http://pypi.python.org/packages/source/p/%{pkgname}/%{pkgname}-%{version}.tar.gz`

But regex tries to match `Source\d`

**Comment by ignatenkobrain** [comment]
@yac ^^^
