### ISSUE TITLE
info-tags-diff not working in 0.41

### ISSUE THREAD

**Issue by apevec** [openstack-packages/rdopkg#82]
++ rdopkg info-tags-diff .
Traceback (most recent call last):
  File "/usr/bin/rdopkg", line 9, in <module>
    load_entry_point('rdopkg==0.41', 'console_scripts', 'rdopkg')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/rdopkg/cli.py", line 5, in <module>
    from rdopkg.core import ActionRunner
  File "/usr/lib/python2.7/site-packages/rdopkg/core.py", line 7, in <module>
    import actions
ImportError: No module named actions

**Comment by yazug** [comment]
seeing this in general after a recent update on fedora 23, all calls to rdopkg throw something like this. even rdopkg --version, let me know if I can dig for what versions of what packages I have

**Comment by apevec** [comment]
Fixed by https://review.rdoproject.org/r/3393

**Comment by yac** [comment]
Thanks! I released `rdopkg-0.41.1` with the fix. Please test that and reopen this if the issue isn't fixed.
